-- TRANSACTIONS:
DROP TABLE
  IF EXISTS TRANSACTIONS;


CREATE TABLE
  IF NOT EXISTS TRANSACTIONS(
    ID SERIAL PRIMARY KEY,
    IS_REVENUE BOOLEAN NULL,
    CATEGORY_ID INTEGER NULL,
    TRANSACTION_DATE DATE NULL,
    TRANSACTION_AMOUNT DOUBLE PRECISION NULL,
    TRANSACTION_DESCRIPTION TEXT NULL,
    COMMENTS TEXT NULL
  );


-- CATEGORIES:
DROP TABLE
  IF EXISTS CATEGORIES;


CREATE TABLE
  IF NOT EXISTS CATEGORIES(
    ID SERIAL PRIMARY KEY,
    LABEL TEXT NOT NULL,
    BREAKDOWN_LABEL TEXT NOT NULL,
    CATEGORY_DESCRIPTION TEXT NULL
  );
